# Generated by Django 5.1.6 on 2025-02-14 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marido', models.CharField(max_length=100)),
                ('nome_esposa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('celular', models.CharField(max_length=14)),
                ('numero_parcelas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='usuarios.cadastro')),
            ],
        ),
    ]
