# Generated by Django 5.1.6 on 2025-02-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cadastro_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='cpf_esposa',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='cpf_marido',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='dt_nasc_esposa',
            field=models.CharField(default=11111111, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='dt_nasc_marido',
            field=models.CharField(default=11111111, max_length=10),
            preserve_default=False,
        ),
    ]
