# Generated by Django 5.1.6 on 2025-03-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_cadastro_cpf_esposa_cadastro_cpf_marido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filho',
            name='cpf_marido',
            field=models.CharField(default=11111111111, max_length=11),
            preserve_default=False,
        ),
    ]
