# Generated by Django 5.1.6 on 2025-02-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('PISCINA', 'Piscina'), ('ACOMODAÇÕES', 'Acomodações'), ('LAZER', 'Laser'), ('GASTRONOMIA', 'Gastronomia')], default='', max_length=100),
        ),
    ]
